apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  type: NodePort
  ports:
  - name: hello-world
    port: 80
    targetPort: hello-world
    nodePort: 30080
  selector:
    app: hello-world