
apiVersion: v1
kind: Service
metadata:
  name: mongoexpress
  labels:
    app: mongoexpress
spec:
  type: NodePort
  ports:
  - name: mongoexpress
    port: 8081
    targetPort: mongoexpress
    nodePort: 30081
  selector:
    app: mongoexpress