name: Publish Docker image
on:
  release:
    tags:
      - 'v*.*.*'
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: update version
        run: |
              echo "${GITHUB_REF##*/}" > ./app/version
              cat ./app/version
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          path: app
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ssadok/sample-node-app
          tag_with_ref: true
      - uses: danielr1996/kubectl-action@1.0.0
        name: deploy to cluster
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
          args: set image --record deployment/hello-world container=ssadok/sample-node-app:${GITHUB_REF##*/}
      - uses: danielr1996/kubectl-action@1.0.0
        name: verify deployment
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
          args: rollout status deployment/hello-world